export const shoppingListActionTypes = {
  ADD_PRODUCT_TO_SHOPPING_LIST: "ADD_PRODUCT_TO_SHOPPING_LIST",
  DELETE_FROM_SHOPPING_LIST: "DELETE_FROM_SHOPPING_LIST",
  GET_SHOPPING_LIST: "GET_SHOPPING_LIST",
};

export const productListActionTypes = {
  ADD_PRODUCT_TO_PRODUCT_LIST: "ADD_PRODUCT_TO_PRODUCT_LIST",
  DELETE_FROM_PRODUCT_LIST: "DELETE_FROM_PRODUCT_LIST",
  GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
};
